package upravljalko;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spelacucko
 */
public class IzbrisiPovezavo extends javax.swing.JFrame {

    /**
     * Creates new form UpravljanjeDelavcev
     */

    
    Povezovanje pov = new Povezovanje(); 
    Skupina sku = new Skupina(); 
    Delavec del = new Delavec(); 

    
    public IzbrisiPovezavo() throws ClassNotFoundException, SQLException {
        initComponents();
        sku.izpisSkupinComboBox(jComboBox_IdSkupine);
        del.izpisDelavcevComboBox(jComboBox_IdDelavca);
        resetirajTabelo(""); 
    }
    
    public static void resetComboDelavec() throws ClassNotFoundException, SQLException{
        Delavec del = new Delavec(); 
        if(jComboBox_IdDelavca != null){
            jComboBox_IdDelavca.removeAllItems();
            del.izpisDelavcevComboBox(jComboBox_IdDelavca);
        }
    }
    
    public static void resetComboSkupina() throws ClassNotFoundException, SQLException{
        Skupina sku = new Skupina();
        if(jComboBox_IdSkupine != null){
           jComboBox_IdSkupine.removeAllItems();
           sku.izpisSkupinComboBox(jComboBox_IdSkupine);
        }
    }
    
    private void getDataTable(){
        int rowIndex = jTable1_seznam_pripadnost.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel)jTable1_seznam_pripadnost.getModel();
        jComboBox_IdDelavca.setSelectedItem(model.getValueAt(rowIndex, 0).toString() + " " + model.getValueAt(rowIndex, 1).toString());
        jComboBox_IdSkupine.setSelectedItem(model.getValueAt(rowIndex, 2).toString());        
    }
    
    public static void resetirajTabelo(String iskalniNiz) throws ClassNotFoundException, SQLException{
        Povezovanje pov = new Povezovanje(); 
        if(jTable1_seznam_pripadnost != null){
            jTable1_seznam_pripadnost.setModel(new DefaultTableModel(null, new Object[]{"Ime", "Priimek", "Skupina"}));
            pov.izpisClanstva(jTable1_seznam_pripadnost, iskalniNiz);
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        izbrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_seznam_pripadnost = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField_najdi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        preklici = new javax.swing.JButton();
        dodaj = new javax.swing.JButton();
        jComboBox_IdSkupine = new javax.swing.JComboBox();
        jComboBox_IdDelavca = new javax.swing.JComboBox();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Skupina:");

        izbrisi.setText("Izbriši");
        izbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbrisiActionPerformed(evt);
            }
        });

        jTable1_seznam_pripadnost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime", "Priimek", "Skupina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1_seznam_pripadnost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_seznam_pripadnostMouseClicked(evt);
            }
        });
        jTable1_seznam_pripadnost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1_seznam_pripadnostKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1_seznam_pripadnostKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_seznam_pripadnost);

        jLabel4.setText("Poišči");

        jTextField_najdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_najdiActionPerformed(evt);
            }
        });
        jTextField_najdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_najdiKeyTyped(evt);
            }
        });

        jLabel3.setText("Delavec:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Izbriši delavca iz skupine");

        preklici.setText("Prekliči");
        preklici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prekliciActionPerformed(evt);
            }
        });

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        jComboBox_IdSkupine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_IdSkupineActionPerformed(evt);
            }
        });

        jComboBox_IdDelavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_IdDelavcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_IdSkupine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_IdDelavca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_najdi))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(0, 73, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(preklici, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izbrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_najdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_IdDelavca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBox_IdSkupine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izbrisi)
                    .addComponent(preklici)
                    .addComponent(dodaj))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private int pridobiIdDelavca() throws ClassNotFoundException, SQLException{
        String imePriimek = (String) jComboBox_IdDelavca.getSelectedItem();
        String[] splitImePriimek = imePriimek.split(" ");
        String ime = splitImePriimek[0];
        String priimek = splitImePriimek[1];
        int delavec_id = del.getIdDelavca(ime, priimek); 
        return delavec_id; 
    }

    private int pridobiIdSkupine() throws ClassNotFoundException, SQLException{
        String nazivSkupine = (String) jComboBox_IdSkupine.getSelectedItem();   
        int skupina_id = sku.getIdSkupine(nazivSkupine);
        return skupina_id; 
    }
       
    private void izbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbrisiActionPerformed
        try {
            int delavec_id = pridobiIdDelavca();
            int skupina_id = pridobiIdSkupine(); 
            if(pov.clanstvo('c', delavec_id, skupina_id, null)){
                pov.dodajOdstraniPovezavo('d', delavec_id, skupina_id, null);
                resetirajTabelo("");
                MainForm.resetirajTabelo("");
            }else{
                JOptionPane.showMessageDialog(null, "Delavec ni član skupine.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(IzbrisiPovezavo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_izbrisiActionPerformed

    private void jTable1_seznam_pripadnostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_seznam_pripadnostMouseClicked
        getDataTable();
    }//GEN-LAST:event_jTable1_seznam_pripadnostMouseClicked

    private void jTable1_seznam_pripadnostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznam_pripadnostKeyPressed

    }//GEN-LAST:event_jTable1_seznam_pripadnostKeyPressed

    private void jTable1_seznam_pripadnostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznam_pripadnostKeyReleased
        getDataTable(); 
    }//GEN-LAST:event_jTable1_seznam_pripadnostKeyReleased

    private void jTextField_najdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_najdiActionPerformed

    }//GEN-LAST:event_jTextField_najdiActionPerformed

    private void jTextField_najdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_najdiKeyTyped
        try { 
            resetirajTabelo(jTextField_najdi.getText());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(IzbrisiPovezavo.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jTextField_najdiKeyTyped

    private void prekliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prekliciActionPerformed
        this.dispose();
    }//GEN-LAST:event_prekliciActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        try {
            DodajPovezavo dpov = new DodajPovezavo();
            dpov.setVisible(true);
            dpov.pack();
            dpov.setLocationRelativeTo(null);
            dpov.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IzbrisiPovezavo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dodajActionPerformed

    private void jComboBox_IdSkupineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_IdSkupineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_IdSkupineActionPerformed

    private void jComboBox_IdDelavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_IdDelavcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_IdDelavcaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new UpravljanjeDelavcev().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JButton izbrisi;
    public static javax.swing.JComboBox jComboBox_IdDelavca;
    public static javax.swing.JComboBox jComboBox_IdSkupine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1_seznam_pripadnost;
    private javax.swing.JTextField jTextField_najdi;
    private javax.swing.JButton preklici;
    // End of variables declaration//GEN-END:variables
}
