package upravljalko;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spelacucko
 */
public class MainForm extends javax.swing.JFrame {
    
    /**
     * Creates new form Forma
     * @param frame
     */
    public static void centreWindow(Window frame){
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    Delavec del = new Delavec();
    Povezovanje pov = new Povezovanje(); 
    
    public MainForm() throws ClassNotFoundException {
        initComponents();
        pov.izpisDelavcevSkupin(jTable1_seznam, ""); 
        centreWindow(this); 
        //jTable1_seznam.setSelectionBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_seznam = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField_najdi = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDodajDelavca = new javax.swing.JMenuItem();
        jMenuItemUpravljajDelavce = new javax.swing.JMenuItem();
        jMenuSkupina = new javax.swing.JMenu();
        jMenuItemDodajSkupino = new javax.swing.JMenuItem();
        jMenuItemUpravljajSkupine = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemDodajVSkupino = new javax.swing.JMenuItem();
        jMenuItemIzbrisiIzSkupine = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1_seznam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ime", "Priimek", "Skupina", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1_seznam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_seznamMouseClicked(evt);
            }
        });
        jTable1_seznam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1_seznamKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1_seznamKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_seznam);

        jLabel4.setText("Poišči delavca: ");

        jTextField_najdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_najdiActionPerformed(evt);
            }
        });
        jTextField_najdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_najdiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_najdi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_najdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        jMenu1.setText("Delavec");

        jMenuItemDodajDelavca.setText("Dodaj delavca");
        jMenuItemDodajDelavca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajDelavcaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDodajDelavca);

        jMenuItemUpravljajDelavce.setText("Upravljaj delavce");
        jMenuItemUpravljajDelavce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpravljajDelavceActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemUpravljajDelavce);

        jMenuBar1.add(jMenu1);

        jMenuSkupina.setText("Skupina");

        jMenuItemDodajSkupino.setText("Dodaj skupino");
        jMenuItemDodajSkupino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajSkupinoActionPerformed(evt);
            }
        });
        jMenuSkupina.add(jMenuItemDodajSkupino);

        jMenuItemUpravljajSkupine.setText("Upravljaj skupine");
        jMenuItemUpravljajSkupine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpravljajSkupineActionPerformed(evt);
            }
        });
        jMenuSkupina.add(jMenuItemUpravljajSkupine);

        jMenuBar1.add(jMenuSkupina);

        jMenu5.setText("Povezovanje");

        jMenuItemDodajVSkupino.setText("Dodaj v skupino");
        jMenuItemDodajVSkupino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDodajVSkupinoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemDodajVSkupino);

        jMenuItemIzbrisiIzSkupine.setText("Izbriši iz skupine");
        jMenuItemIzbrisiIzSkupine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIzbrisiIzSkupineActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemIzbrisiIzSkupine);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void resetirajTabelo(String iskalniNiz) throws ClassNotFoundException{
       Povezovanje pov = new Povezovanje(); 
        jTable1_seznam.setModel(new DefaultTableModel(null, new Object[]{"Id", "Ime", "Priimek", "Skupina", "Status"}));
        pov.izpisDelavcevSkupin(jTable1_seznam, iskalniNiz);
    }
          
    private void jTable1_seznamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_seznamMouseClicked

    }//GEN-LAST:event_jTable1_seznamMouseClicked

    private void jTable1_seznamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznamKeyPressed
        
    }//GEN-LAST:event_jTable1_seznamKeyPressed

    private void jTextField_najdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_najdiActionPerformed
        
    }//GEN-LAST:event_jTextField_najdiActionPerformed

    private void jTextField_najdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_najdiKeyTyped
        try {
            resetirajTabelo(jTextField_najdi.getText()); 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_najdiKeyTyped

    private void jTable1_seznamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznamKeyReleased
 
    }//GEN-LAST:event_jTable1_seznamKeyReleased

    private void jMenuItemUpravljajSkupineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpravljajSkupineActionPerformed
        try {
            UpravljanjeSkupin uprSk = new UpravljanjeSkupin();
            uprSk.setVisible(true);
            uprSk.pack();
            uprSk.setLocationRelativeTo(null);
            uprSk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemUpravljajSkupineActionPerformed

    private void jMenuItemDodajSkupinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajSkupinoActionPerformed
        try {
            DodajSkupino dodSk = new DodajSkupino();
            dodSk.setVisible(true);
            dodSk.pack();
            dodSk.setLocationRelativeTo(null);
            dodSk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemDodajSkupinoActionPerformed

    private void jMenuItemDodajDelavcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajDelavcaActionPerformed
        DodajDelavca dodDel = new DodajDelavca();
        dodDel.setVisible(true);
        dodDel.pack();
        dodDel.setLocationRelativeTo(null);
        dodDel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemDodajDelavcaActionPerformed

    private void jMenuItemUpravljajDelavceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpravljajDelavceActionPerformed
        try {
            UpravljanjeDelavcev uprDel = new UpravljanjeDelavcev();
            uprDel.setVisible(true);
            uprDel.pack();
            uprDel.setLocationRelativeTo(null);
            uprDel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemUpravljajDelavceActionPerformed

    private void jMenuItemDodajVSkupinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDodajVSkupinoActionPerformed
        try {
            DodajPovezavo dpov = new DodajPovezavo();
            dpov.setVisible(true);
            dpov.pack();
            dpov.setLocationRelativeTo(null);
            dpov.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemDodajVSkupinoActionPerformed

    private void jMenuItemIzbrisiIzSkupineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIzbrisiIzSkupineActionPerformed
        try {
            IzbrisiPovezavo ipov = new IzbrisiPovezavo();
            ipov.setVisible(true);
            ipov.pack();
            ipov.setLocationRelativeTo(null);
            ipov.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemIzbrisiIzSkupineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new MainForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemDodajDelavca;
    private javax.swing.JMenuItem jMenuItemDodajSkupino;
    private javax.swing.JMenuItem jMenuItemDodajVSkupino;
    private javax.swing.JMenuItem jMenuItemIzbrisiIzSkupine;
    private javax.swing.JMenuItem jMenuItemUpravljajDelavce;
    private javax.swing.JMenuItem jMenuItemUpravljajSkupine;
    private javax.swing.JMenu jMenuSkupina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1_seznam;
    private javax.swing.JTextField jTextField_najdi;
    // End of variables declaration//GEN-END:variables

}
                    
 
