package upravljalko;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spelacucko
 */
public class UpravljanjeDelavcev extends javax.swing.JFrame {

    /**
     * Creates new form UpravljanjeDelavcev
     */
    
    Delavec del = new Delavec();
    
    public UpravljanjeDelavcev() throws ClassNotFoundException, SQLException {
        initComponents();
        del.izpisDelavcev(jTable1_seznam_delavcev, ""); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_ime = new javax.swing.JTextField();
        jTextField_priimek = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        posodobi = new javax.swing.JButton();
        izbrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_seznam_delavcev = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField_najdi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        preklici = new javax.swing.JButton();
        dodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_ime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_imeActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime:");

        jLabel2.setText("Priimek:");

        posodobi.setText("Posodobi");
        posodobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posodobiActionPerformed(evt);
            }
        });

        izbrisi.setText("Izbriši");
        izbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbrisiActionPerformed(evt);
            }
        });

        jTable1_seznam_delavcev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ime", "Priimek"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1_seznam_delavcev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_seznam_delavcevMouseClicked(evt);
            }
        });
        jTable1_seznam_delavcev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1_seznam_delavcevKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1_seznam_delavcevKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_seznam_delavcev);

        jLabel4.setText("Poišči delavca: ");

        jTextField_najdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_najdiActionPerformed(evt);
            }
        });
        jTextField_najdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_najdiKeyTyped(evt);
            }
        });

        jLabel3.setText("Id:");

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Upravljaj delavce");

        preklici.setText("Prekliči");
        preklici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prekliciActionPerformed(evt);
            }
        });

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel3))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_priimek)
                                    .addComponent(jTextField_id, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_ime)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_najdi))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(84, Short.MAX_VALUE)
                        .addComponent(preklici, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izbrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posodobi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_najdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_ime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_priimek, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posodobi)
                    .addComponent(izbrisi)
                    .addComponent(preklici)
                    .addComponent(dodaj))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void resetirajTabelo(String iskalniNiz) throws ClassNotFoundException, SQLException{
        Delavec del = new Delavec(); 
        if(jTable1_seznam_delavcev != null){
            jTable1_seznam_delavcev.setModel(new DefaultTableModel(null, new Object[]{"Id", "Ime", "Priimek"}));
            del.izpisDelavcev(jTable1_seznam_delavcev, iskalniNiz);
        }
    }
           
    private void getDataTable(){
        int rowIndex = jTable1_seznam_delavcev.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel)jTable1_seznam_delavcev.getModel();
        jTextField_id.setText(model.getValueAt(rowIndex, 0).toString()); 
        jTextField_ime.setText(model.getValueAt(rowIndex, 1).toString()); 
        jTextField_priimek.setText(model.getValueAt(rowIndex, 2).toString()); 
    }
    
    private boolean verifyText(){
        if(jTextField_ime.getText().equals("") || jTextField_priimek.getText().equals("") || jTextField_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Eno ali več polij je praznih!");
            return false; 
        }else{
           return true; 
        }
    }
       
    private void jTextField_imeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_imeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_imeActionPerformed

    private void posodobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posodobiActionPerformed
        if(verifyText()){
            int id = Integer.valueOf(jTextField_id.getText());
            String ime = jTextField_ime.getText();
            String priimek = jTextField_priimek.getText();
            try {
                if(!del.obstojDelavca(ime, priimek)){
                    del.dodajPosodobiBrisiDelavca('u', ime, priimek, id);
                    //Resetiraj tabele in comboboxe
                    resetirajTabelo("");
                    MainForm.resetirajTabelo("");
                    IzbrisiPovezavo.resetComboDelavec();
                    IzbrisiPovezavo.resetComboSkupina();
                    IzbrisiPovezavo.resetirajTabelo("");
                    DodajPovezavo.resetComboDelavec();
                    DodajPovezavo.resetComboSkupina();
                }else{
                    if(del.spremembe(ime, priimek, id)){
                        JOptionPane.showMessageDialog(null, "Ni bilo vnesenih sprememb");
                    }else{
                        JOptionPane.showMessageDialog(null, "Delavec s takšnim imenom in priimkom že obstaja!");
                    }
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_posodobiActionPerformed

    private void izbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbrisiActionPerformed
        if(jTextField_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Delavec ni izbran.");
        }else{
            try {
                int id = Integer.valueOf(jTextField_id.getText());
                del.dodajPosodobiBrisiDelavca('d', null, null, id);
                //Resetiraj tabele in comboboxe
                resetirajTabelo("");
                MainForm.resetirajTabelo("");
                IzbrisiPovezavo.resetComboDelavec();
                IzbrisiPovezavo.resetComboSkupina();
                IzbrisiPovezavo.resetirajTabelo("");
                DodajPovezavo.resetComboDelavec();
                DodajPovezavo.resetComboSkupina();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_izbrisiActionPerformed

    private void jTable1_seznam_delavcevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_seznam_delavcevMouseClicked
        getDataTable();
    }//GEN-LAST:event_jTable1_seznam_delavcevMouseClicked

    private void jTable1_seznam_delavcevKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznam_delavcevKeyPressed

    }//GEN-LAST:event_jTable1_seznam_delavcevKeyPressed

    private void jTable1_seznam_delavcevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznam_delavcevKeyReleased
        getDataTable();
    }//GEN-LAST:event_jTable1_seznam_delavcevKeyReleased

    private void jTextField_najdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_najdiActionPerformed

    }//GEN-LAST:event_jTextField_najdiActionPerformed

    private void jTextField_najdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_najdiKeyTyped
        try {
            resetirajTabelo(jTextField_najdi.getText()); 
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_najdiKeyTyped

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void prekliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prekliciActionPerformed
        this.dispose();
    }//GEN-LAST:event_prekliciActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        DodajDelavca dodDel = new DodajDelavca();
        dodDel.setVisible(true);
        dodDel.pack();
        dodDel.setLocationRelativeTo(null);
        dodDel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_dodajActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new UpravljanjeDelavcev().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(UpravljanjeDelavcev.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JButton izbrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1_seznam_delavcev;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_ime;
    private javax.swing.JTextField jTextField_najdi;
    private javax.swing.JTextField jTextField_priimek;
    private javax.swing.JButton posodobi;
    private javax.swing.JButton preklici;
    // End of variables declaration//GEN-END:variables
}
