package upravljalko;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spelacucko
 */
public class UpravljanjeSkupin extends javax.swing.JFrame {

    /**
     * Creates new form UpravljanjeSkupin
     */
    Skupina skup = new Skupina(); 
    Delavec del = new Delavec(); 
    
    public UpravljanjeSkupin() throws ClassNotFoundException, SQLException {
        initComponents();
        skup.izpisSkupin(jTable1_seznam_skupin, "");
//        jTable1_seznam.setRowHeight(40);
//        jTable1_seznam.setShowGrid(true);
//        jTable1_seznam.setSelectionBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        posodobi = new javax.swing.JButton();
        izbrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_seznam_skupin = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField_najdi = new javax.swing.JTextField();
        jTextField_naziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        preklici = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel1.setText("Naziv");

        posodobi.setText("Posodobi");
        posodobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posodobiActionPerformed(evt);
            }
        });

        izbrisi.setText("Izbriši");
        izbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izbrisiActionPerformed(evt);
            }
        });

        jTable1_seznam_skupin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Naziv"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1_seznam_skupin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_seznam_skupinMouseClicked(evt);
            }
        });
        jTable1_seznam_skupin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1_seznam_skupinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1_seznam_skupinKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_seznam_skupin);

        jLabel4.setText("Poišči skupino: ");

        jTextField_najdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_najdiActionPerformed(evt);
            }
        });
        jTextField_najdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_najdiKeyTyped(evt);
            }
        });

        jTextField_naziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nazivActionPerformed(evt);
            }
        });

        jLabel3.setText("Id:");

        preklici.setText("Prekliči");
        preklici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prekliciActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Upravljaj skupine");

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_najdi))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_naziv)
                            .addComponent(jTextField_id)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addComponent(preklici, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izbrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posodobi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodaj)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_najdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izbrisi)
                    .addComponent(posodobi)
                    .addComponent(preklici)
                    .addComponent(dodaj))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    public static void resetirajTabelo(String iskalniNiz) throws ClassNotFoundException, SQLException{
        Skupina skup = new Skupina(); 
        if(jTable1_seznam_skupin != null){
            jTable1_seznam_skupin.setModel(new DefaultTableModel(null, new Object[]{"Id", "Naziv"}));
            skup.izpisSkupin(jTable1_seznam_skupin, iskalniNiz);
        }
    }
        
    private void getDataTable(){
        int rowIndex = jTable1_seznam_skupin.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel)jTable1_seznam_skupin.getModel();
        jTextField_id.setText(model.getValueAt(rowIndex, 0).toString()); 
        jTextField_naziv.setText(model.getValueAt(rowIndex, 1).toString()); 
    }
    
    private boolean verifyText(){
        if(jTextField_naziv.getText().equals("") || jTextField_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Eno ali več polij je praznih!");
            return false; 
        }else{
           return true; 
        }
    }    
    
    private void posodobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posodobiActionPerformed

        if(verifyText()){       
            int id = Integer.valueOf(jTextField_id.getText());
            String naziv = jTextField_naziv.getText();
            try {
                if(!skup.obstojSkupine(naziv)){
                    skup.dodajPosodobiBrisiSkupino('u', naziv, id);
                    //Resetiraj tabele in comboboxe
                    resetirajTabelo("");
                    MainForm.resetirajTabelo("");
                    IzbrisiPovezavo.resetComboDelavec();
                    IzbrisiPovezavo.resetComboSkupina();
                    IzbrisiPovezavo.resetirajTabelo("");
                    DodajPovezavo.resetComboDelavec();
                    DodajPovezavo.resetComboSkupina();
                }else{
                    if(skup.spremembe(naziv, id)){
                        JOptionPane.showMessageDialog(null, "Ni bilo vnesenih sprememb");
                    }else{
                        JOptionPane.showMessageDialog(null, "Skupina že obstaja!");
                    }
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UpravljanjeSkupin.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_posodobiActionPerformed

    private void izbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izbrisiActionPerformed
        if(jTextField_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Skupina ni izbran.");
        }else{
            try {
                int id = Integer.valueOf(jTextField_id.getText());
                skup.dodajPosodobiBrisiSkupino('d', null, id);
                //Resetiraj tabele in comboboxe
                resetirajTabelo("");
                MainForm.resetirajTabelo("");
                IzbrisiPovezavo.resetComboDelavec();
                IzbrisiPovezavo.resetComboSkupina();
                IzbrisiPovezavo.resetirajTabelo("");
                DodajPovezavo.resetComboDelavec();
                DodajPovezavo.resetComboSkupina();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UpravljanjeSkupin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_izbrisiActionPerformed

    private void jTable1_seznam_skupinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_seznam_skupinMouseClicked
        getDataTable();
    }//GEN-LAST:event_jTable1_seznam_skupinMouseClicked

    private void jTable1_seznam_skupinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznam_skupinKeyPressed

    }//GEN-LAST:event_jTable1_seznam_skupinKeyPressed

    private void jTable1_seznam_skupinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_seznam_skupinKeyReleased
        getDataTable();
    }//GEN-LAST:event_jTable1_seznam_skupinKeyReleased

    private void jTextField_najdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_najdiActionPerformed

    }//GEN-LAST:event_jTextField_najdiActionPerformed

    private void jTextField_najdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_najdiKeyTyped
        try {
            resetirajTabelo(jTextField_najdi.getText());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UpravljanjeSkupin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_najdiKeyTyped

    private void jTextField_nazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nazivActionPerformed

    private void prekliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prekliciActionPerformed
        this.dispose(); 
    }//GEN-LAST:event_prekliciActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        try {
            DodajSkupino dodSk = new DodajSkupino();
            dodSk.setVisible(true);
            dodSk.pack();
            dodSk.setLocationRelativeTo(null);
            dodSk.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpravljanjeSkupin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dodajActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeSkupin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeSkupin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeSkupin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpravljanjeSkupin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new UpravljanjeSkupin().setVisible(true);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(UpravljanjeSkupin.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JButton izbrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1_seznam_skupin;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_najdi;
    private javax.swing.JTextField jTextField_naziv;
    private javax.swing.JButton posodobi;
    private javax.swing.JButton preklici;
    // End of variables declaration//GEN-END:variables

    void setLocationRelevantTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
